INSERT INTO public.frame(inspection_id, box_number, frame_name, comb_pattern, honey, nectar, brood, queen_spotted, cells)
	VALUES (1, '3', '1A', 'Good', 'Full', 'None', 'None', true, 'Super Queen'),
			(1, '3', '1B', 'Good', 'Full', 'None', 'None', false, 'Super Queen'),
			(1, '3', '2A', 'Good', 'Full', 'None', 'None', false, 'Super Queen'),
			(1, '3', '2B', 'Good', 'Full', 'None', 'None', false, 'Super Queen'),
			(1, '3', '3A', 'Good', 'Full', 'None', 'None', false, 'Super Queen'),
			(1, '3', '3B', 'Good', 'Full', 'None', 'None', false, 'Super Queen'),
			(1, '2', '1A', 'Good', 'Full', 'None', 'None', false, 'Super Queen'),
			(1, '2', '1B', 'Good', 'Full', 'None', 'None', false, 'Super Queen'),
			(1, '2', '2A', 'Good', 'Full', 'None', 'None', false, 'Super Queen'),
			(1, '2', '2B', 'Good', 'Full', 'None', 'None', false, 'Super Queen'),
			(1, '2', '3A', 'Good', 'Full', 'None', 'None', false, 'Super Queen'),
			(1, '2', '3B', 'Good', 'Full', 'None', 'None', false, 'Super Queen'),
			(1, '1', '1A', 'Good', 'Full', 'None', 'None', false, 'Super Queen'),
			(1, '1', '1B', 'Good', 'Full', 'None', 'None', false, 'Super Queen'),
			(1, '1', '2A', 'Good', 'Full', 'None', 'None', false, 'Super Queen'),
			(1, '1', '2B', 'Good', 'Full', 'None', 'None', false, 'Super Queen'),
			(1, '1', '3A', 'Good', 'Full', 'None', 'None', false, 'Super Queen'),
			(1, '1', '3B', 'Good', 'Full', 'None', 'None', false, 'Super Queen');